### PR TITLE
Add Elasticsearch variables mapping

### PR DESCRIPTION
**Pull request by maximgubar**

### CODE REVIEW

**Comment by Crell** [comment]
Hi @maximgubar!

Are these variable names standardized by Symfony?  I didn't see that in the documentation anywhere, and the PR also doesn't add any Symfony-side configuration to leverage them the way that Doctrine and Mongo do.  What library uses these, and where is its documentation?

**Comment by Crell** [comment]
This will also need tests.  Everything needs tests. :smile:

**Comment by maximgubar** [comment]
Hi @Crell !
Yes, you are right, symfony itself doesnt use this variables, but there are bundles, which require elasticsearch credentials, they are not expecting exactly this vars, but anyway, I thought that it would make sense to expose them, so any other 3rd party code could use it.
Regarding the tests, sure, I'll write them, just let me know if it make sense) I mean if the PR is going to be merged.

**Comment by Crell** [comment]
The lack of a standard convention for what they should be is my concern. If there (say) 3 bundles that all want different env vars, then we would have to pick one and privilege it or set all 3.  I don't care for either option.  If there is a standard set of env var names, either formally or de facto, then we should definitely go ahead and set them and try to wire them up in Symfony itself.

Have any links to resources to help determine which it is?

**Comment by maximgubar** [comment]
we are using [FOSElasticaBundle](https://github.com/FriendsOfSymfony/FOSElasticaBundle), but as I said, it doesnt require env vars

**Comment by Crell** [comment]
Mm, so with that one, what you'd have to do is map to "Some env vars" and then reference those env vars from the YAML config.  Have a look at the Mongo config in the library now, which documents exactly how to do that for Mongo.  I'd accept something equivalent for Elastica.

**Comment by Crell** [comment]
Continuing in #33.

**Pull request closed without merging**
